# Generated by scripts/sync-method-catalogue.mjs. Do not edit.
# Source: schemas/profiles/chap-methods.schema.json
"""Which profile owns which method, and which methods are never gated.

SPECIFICATION 15.4: a Coordinator refuses a method whose owning profile the
workspace does not advertise. The rule is per method rather than per namespace,
because six of the twelve namespaces span profiles: workspace covers core,
modes and control; participant covers core and security-signed; task, review
and escalate each straddle their home profile and routing; audit covers core
and audit-scitt.
"""
from __future__ import annotations

#: The profile that introduces each method the references implement.
OWNING_PROFILE: dict[str, str] = {
    "abstain.declare":         "review/1.0",
    "audit.read":              "core/1.0",
    "audit.submit_to_scitt":   "audit-scitt/1.0",
    "audit.verify_chain":      "audit-scitt/1.0",
    "audit.verify_receipt":    "audit-scitt/1.0",
    "control.cancel":          "control/1.0",
    "control.pause":           "control/1.0",
    "control.resume":          "control/1.0",
    "control.rollback":        "control/1.0",
    "control.set_mode_ceiling":"control/1.0",
    "control.snapshot":        "control/1.0",
    "control.supersede":       "control/1.0",
    "decide.approve":          "review/1.0",
    "decide.override":         "review/1.0",
    "decide.reject":           "review/1.0",
    "deliberate.close":        "deliberation/1.0",
    "deliberate.comment":      "deliberation/1.0",
    "deliberate.open":         "deliberation/1.0",
    "deliberate.vote":         "deliberation/1.0",
    "escalate.auto":           "routing/1.0",
    "escalate.raise":          "review/1.0",
    "handoff.accept":          "handoff/1.0",
    "handoff.decline":         "handoff/1.0",
    "handoff.propose":         "handoff/1.0",
    "participant.join":        "core/1.0",
    "participant.leave":       "core/1.0",
    "participant.revoke_key":  "core/1.0",
    "participant.rotate_key":  "core/1.0",
    "review.depth":            "routing/1.0",
    "review.request":          "review/1.0",
    "task.complete":           "core/1.0",
    "task.create":             "core/1.0",
    "task.route":              "routing/1.0",
    "task.update":             "core/1.0",
    "whisper.answer":          "whisper/1.0",
    "whisper.ask":             "whisper/1.0",
    "workspace.create":        "core/1.0",
    "workspace.describe":      "core/1.0",
    "workspace.set_profiles":  "core/1.0",
}

#: Callable whatever the workspace advertises.
#:
#: Reads, because a workspace must always be able to ask what it is and to
#: check its own chain. Not the coordinator's read-only set: that holds
#: audit.submit_to_scitt, which reaches a transparency service and is a real
#: audit-scitt/1.0 capability.
ALWAYS_AVAILABLE: frozenset[str] = frozenset({
    "workspace.describe",
    "audit.read",
    "audit.verify_chain",
    "audit.verify_receipt",
})
