"""
Build and execute examples/chap_analytics_walkthrough.ipynb.

The notebook is generated from this file so its prose and code live in one
reviewable place, and executed so the committed copy shows real output.

    python examples/build_notebook.py            # write and execute
    python examples/build_notebook.py --no-run   # write only
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = Path(__file__).resolve().parent
TARGET = HERE / "chap_analytics_walkthrough.ipynb"

CELLS: list[tuple[str, str]] = []


def md(text: str) -> None:
    CELLS.append(("markdown", text.strip("\n")))


def code(text: str) -> None:
    CELLS.append(("code", text.strip("\n")))


# --------------------------------------------------------------------------
md("""
# From CHAP envelopes to dataframes

A CHAP coordinator keeps an audit log of everything humans and agents did
together in a workspace: every task created, every draft submitted, every
approval, correction, question, handoff and vote. Each entry is a JSON-RPC
envelope, and where the coordinator chains its log each entry is hash-linked
to the one before it.

`chap-analytics` reads that log and projects it into eleven pandas tables.
This notebook follows one week of work through the whole pipeline: the raw
envelopes as `audit.read` returns them; a `Chain`, which is the package's view
of a workspace; `frames()`, which replays the chain into tables; the contract
each table keeps; the tables themselves; the analyses they make routine; what
an MCP client with `audit.read` alone can recover, and how the tables say where
they are unsure; redaction; and export.

Everything below runs against a real coordinator. The week is generated by
`chap_analytics.sample`, so the numbers reflect the coordinator that is
installed and are the same for the same seed.
""")

md("""
## Setup

`pandas` is the package's only dependency. Generating the sample week drives a
coordinator in this process, which needs `chap-coordinator` as well:

```bash
pip install 'chap-analytics[coordinator]'
```
""")

code("""
import json
import pandas as pd

from chap_analytics import Chain, frames, from_coordinator, describe, redact_artefacts
from chap_analytics.sample import WORKSPACE, support_desk_coordinator

pd.set_option("display.width", 140)
pd.set_option("display.max_columns", 30)

coord = support_desk_coordinator(seed=7)
""")

md("""
## 1. The envelopes

`audit.read` is a CHAP method like any other, and it is what an MCP client can
call to get the log. Each entry carries its position in the log (`seq`), when
the coordinator accepted it (`arrived`), the hash link to the previous entry
(`prev_hash`, present because this coordinator chains its log), and the
envelope itself: the method, and the request parameters exactly as the caller
sent them.

The sample coordinator runs a deterministic clock, so `arrived` is an
artificial timeline. The sender stamps its own `ts` into every envelope, and
that carries the week.
""")

code("""
result = coord.dispatch({
    "jsonrpc": "2.0", "id": "read", "method": "audit.read",
    "params": {"workspace": WORKSPACE, "from": "human:maya"},
})
entries = result["result"]["entries"]
print(f"{len(entries)} entries in the log")
pd.Series([e["envelope"]["method"] for e in entries]).value_counts().rename("count").to_frame()
""")

md("""
Three entries show the shape. A `task.create` names the work, who is to do it,
and the routing hints it arrived with. A `review.request` carries the artefact
under review. A `decide.override` carries the RFC 6902 patch the reviewer
applied, their rationale, and the tags and policy references they attached.

Server-minted identifiers, such as the id of a task, are returned to the caller
in the *result* of the call. The audit log records the envelopes, so a task's
id becomes visible in the log when a later envelope acts on it. That detail
matters later.
""")

code("""
def first(method):
    return next(e for e in entries if e["envelope"]["method"] == method)

for method in ("task.create", "review.request", "decide.override"):
    entry = first(method)
    print(f"seq {entry['seq']}  arrived {entry['arrived']}  prev_hash {entry.get('prev_hash')}")
    print(json.dumps(entry["envelope"]["params"], indent=1), "\\n")
""")

md("""
## 2. A `Chain`

A `Chain` is one workspace's history, ready to project: the envelope stream,
plus whatever server state the source carried. The four loaders return one:

```python
from chap_analytics import from_sqlite, from_url, from_json, from_coordinator

from_sqlite("./chap.db", workspace="wsp_support")     # the coordinator's SQLite file
from_url("http://localhost:8080/chap", "wsp_support") # a running coordinator, via audit.read
from_json("export.json")                              # an audit.read result, a bare entry list, or a snapshot
from_coordinator(coord, workspace="wsp_support")      # a Coordinator object in this process
```

A SQLite file or a live coordinator carries the workspace snapshot beside the
log; `audit.read` carries the log. `chain.has_state` says which you have, and
the tables say what that changes. Both are built here so the two reads can be
compared at the end. There is no HTTP server in this notebook, so the
envelope-only chain is built directly from the `audit.read` result;
`support_desk(envelopes_only=True)` does the same in one call.
""")

code("""
with_state = from_coordinator(coord, workspace=WORKSPACE)
envelopes_only = Chain(workspace=WORKSPACE, events=entries, state=None, source="audit.read")

print(with_state)
print(envelopes_only)
print()
print(with_state.summary())
""")

md("""
## 3. `frames()`

`frames(chain)` replays the envelope stream once into an index of what
happened, then builds every table as a view over that index. Replaying the
envelopes is what lets the whole layer work from `audit.read` alone: the
artefact under review arrives on `review.request` and the patch on
`decide.override`, so the before and the after of every correction are in the
log. The snapshot adds what the server computed: deliberation and routing
outcomes.
""")

code("""
f = frames(with_state)
print(f.summary())
""")

md("""
## 4. The contract

Every column is declared in `schema.py` with its dtype and its provenance, and
`frames()` enforces the declaration: every table has exactly those columns, in
that order, with those dtypes. A column the source lacked a value for is
present and null, so downstream code can reference any column whatever the
chain came from.

Provenance has four values:

| Provenance | Meaning |
|---|---|
| `envelopes` | Read straight from a request parameter. |
| `state` | Computed by the server and carried in the snapshot. Null from `audit.read` alone. |
| `replay` | Derived by replaying the envelope stream. Available from either source. |
| `derived` | Computed from the other columns: counts, durations, flags, labels. |

`describe()` prints the whole contract; `print(describe())` shows every table.
The `tasks` block is shown here.
""")

code("""
blocks = describe().split("\\n\\n")
print(next(b for b in blocks if b.startswith("tasks")))
""")

md("""
## 5. The tables

Each table has one grain, stated in `schema.py`. The sections below show the
first rows and the dtypes of each, and the columns worth knowing.
""")

md("""
### `events`: one row per audit log entry

The chain itself, flattened. Every other table is a projection of this one, so
every count elsewhere reconciles with a count here. `ts` is the sender's
timestamp and `arrived` is the coordinator's; `actor_kind` is the URI scheme of
whoever made the call.
""")

code("""
f.events.head(8)
""")

code("""
f.events.dtypes.to_frame("dtype")
""")

md("""
### `tasks`: one row per task

A task and how it ended. The lifecycle columns are replayed from state
transitions, so they hold from envelopes alone.

- `outcome` says how the task ended. Where a review settled it, the value is
  read from the decision that settled the last pass: `approved`, `overridden`,
  `rejected` or `abstained`. Otherwise it is the state the task reached:
  `escalated`, `cancelled`, `superseded`, `declined`,
  `completed_after_rejection`, `completed_bypassing_review`,
  `completed_without_review` or `open`.
- `settled` and `lifetime_s` censor open work: a task still running when the
  chain was read has a null lifetime, and the flag says so.
- `n_reviews` counts review passes. A task sent back for revision is reviewed
  again, and each pass judged its own artefact.
- `confidence` is the agent's self-reported confidence, parsed from its
  decimal-string wire form into a float.
- `id_certain` and `assignee_certain` say how sure the projection is about the
  row; section 7 explains them.
""")

code("""
f.tasks[["task_id", "kind", "assignee", "state", "outcome", "settled", "lifetime_s",
         "n_reviews", "n_decisions", "confidence", "criticality", "id_certain"]].head(10)
""")

code("""
f.tasks.dtypes.to_frame("dtype")
""")

md("""
### `decisions`: one row per approve, reject, override or abstain

The unit of analysis for anything about reviewers. `review_index` says which
pass on the task a decision belongs to, `is_final` whether it settled that
pass, and `latency_s` is measured from the opening of the decision's own pass.
`is_final` is computed with the coordinator's own rule: under `quorum:2` the
second approval settles the review, and under `all_approve` the last named
reviewer does.
""")

code("""
f.decisions[["task_id", "reviewer", "kind", "rule", "review_index", "decision_index",
             "is_final", "latency_s", "request_revision", "tags"]].head(10)
""")

code("""
f.decisions.dtypes.to_frame("dtype")
""")

md("""
### `overrides`: one row per correction

The supervision signal: what a human changed, why, and whether they refined the
agent's decision or reversed it. `based_on` is the artefact the reviewer saw,
reconstructed from the review request; `result` is the patch applied to it,
with the coordinator's own RFC 6902 semantics. Both are available from
`audit.read` alone. `intent_preserved` is the reviewer's own statement of
whether the edit refined or reversed the draft's decision.
""")

code("""
cols = ["task_id", "reviewer", "rationale", "tags", "policy_refs", "intent_preserved",
        "n_ops", "op_kinds", "paths", "top_path", "confidence"]
f.overrides[cols].head()
""")

code("""
first_override = f.overrides.iloc[0]
print("before:", json.dumps(first_override["based_on"]))
print("after: ", json.dumps(first_override["result"]))
""")

md("""
### `patch_ops`: one row per RFC 6902 operation

Overrides exploded to the operation. This is the grain that answers which field
of an output gets corrected most: group by `top_path`.
""")

code("""
f.patch_ops.head()
""")

md("""
### `participants`: one row per participant

Who was involved and what they did, with the counts denormalised so a reviewer
league table is one frame.
""")

code("""
f.participants
""")

md("""
### `deliberations` and `votes`

Group decisions and the individual votes cast in them. `outcome` is computed by
the server at close, so it comes from the snapshot and is null from
`audit.read` alone. Turnout is votes over participants.
""")

code("""
f.deliberations[["question", "opener", "rule", "n_participants", "n_votes",
                 "n_yea", "n_nay", "turnout", "outcome", "id_certain"]]
""")

code("""
f.votes[["voter", "vote", "ts", "veto_invoked"]]
""")

md("""
### `whispers`: one row per deadline-bound question

An agent's question to a person, with a deadline and a default. `state` is what
the coordinator holds: `pending`, `answered` or `lapsed`. `lapsed` is true where
the deadline passed before an answer arrived, or the coordinator announced the
lapse and applied the default. A high lapse rate means the agents needed a
person who was elsewhere.
""")

code("""
f.whispers[["question", "asker", "deadline_ms", "answered", "answered_by", "answer",
            "state", "lapsed", "response_s", "id_certain"]]
""")

md("""
### `handoffs`: one row per proposed handoff

Work passed between participants. `resolution` is `accepted`, `declined` or
`open`; a handoff offered to a group stays open when one member declines,
because the rest may still take it.
""")

code("""
f.handoffs[["proposer", "recipient", "n_tasks", "resolution", "resolved_by",
            "n_accepted", "response_s", "id_certain"]]
""")

md("""
### `routing`: one row per routing decision

What the routing policy chose and why, for workspaces that run the
`routing/1.0` profile. The support desk runs core, review, whisper,
deliberation, handoff and control, so the table is empty here. It still has
every declared column.
""")

code("""
print(len(f.routing), "rows")
f.routing.dtypes.to_frame("dtype")
""")

md("""
## 6. The analyses

Each of these is a count or a median, with a line on what it is for. A week is
a small sample, and the intervals that would make these into statements belong
to stage 2 of the roadmap.
""")

md("""
**How the week ended.** The overridden share is the supervision signal.
""")

code("""
drafts = f.tasks[f.tasks["kind"] == "draft_reply"]
drafts["outcome"].value_counts().rename("tasks").to_frame()
""")

md("""
**What reviewers keep correcting, and why.** Which field gets corrected says
where to look in the output. Which tag leads says what kind of change to make.
""")

code("""
f.patch_ops.groupby("top_path").size().rename("corrections").to_frame()
""")

code("""
f.overrides.explode("tags").groupby("tags").size().rename("overrides").sort_values(ascending=False).to_frame()
""")

md("""
**Refining or reversing.** A refinement keeps the draft's decision and changes
how it is expressed or supported. A reversal substitutes a different decision.
A reviewer may leave the flag unsaid, and that share is worth seeing too.
""")

code("""
(f.overrides["intent_preserved"].map({True: "refined", False: "reversed"})
 .value_counts(dropna=False).rename("overrides").to_frame())
""")

md("""
**Does the agent's confidence mean anything?** Overridden drafts should be the
less confident ones. Two medians are what a week supports; reliability diagrams
and a Brier score are stage 3.
""")

code("""
judged = drafts[drafts["outcome"].isin(["approved", "overridden"])]
judged.groupby("outcome")["confidence"].agg(["count", "median", "min", "max"]).round(2)
""")

md("""
**The reviewers.** Decisions, corrections and abstentions per person, with the
median time from a review opening to their decision.
""")

code("""
league = f.participants[f.participants["kind"] == "human"][
    ["participant", "n_decisions", "n_overrides", "n_abstentions"]].set_index("participant")
league["median_minutes"] = (f.decisions.groupby("reviewer")["latency_s"].median() / 60).round(0)
league
""")

md("""
**Time to a decision.** Elapsed time, which is what the chain records, with
open work censored: the tasks still running at the end of the week are left
out of the figures.
""")

code("""
final = f.decisions[f.decisions["is_final"]]["latency_s"] / 60
print(f"{len(final)} reviews settled; median {final.median():.0f} min, 90th percentile {final.quantile(0.9):.0f} min")
print(f"{int((~f.tasks['settled']).sum())} tasks still open, excluded from the figures above")
print(f"{int((f.tasks['n_reviews'] > 1).sum())} task(s) sent back and reviewed again")
print()
print("Every task, by how it ended:")
print(f.tasks["outcome"].value_counts().to_string())
print("(completed_without_review are the three replies handed to Sam and written by hand)")
""")

md("""
## 7. The same tables from `audit.read` alone

An MCP client holds the envelopes. Everything above is available to it, with
three exceptions that the tables mark.

Deliberation and routing outcomes are computed by the server, so their
provenance is `state` and they are null from envelopes alone.

A `task.route` names the assignee it chose in the result of the call, so from
envelopes alone the task keeps its pre-routing assignee and `assignee_certain`
is false. The same flag goes false where an acceptance moved a task and the
offer it belongs to is itself inferred.

Server-minted ids are returned in the result of the creating call, so from
envelopes alone the projection pairs each creation with the first unclaimed id
it sees later. That pairing is a reading when work proceeds one task at a
time, and an inference when two tasks are created before either is touched.
`id_certain` says which case a row is in, and the protocol settles many cases
on its own: a lapse concerns a whisper whose deadline had passed, an answer
comes from someone the whisper was addressed to, a vote from an invited
participant, an acceptance from the named recipient. `frames.summary()`
reports how many rows remain inferred.
""")

code("""
g = frames(envelopes_only)
print(g.summary())
""")

code("""
comparison = pd.DataFrame({
    "with state": f.tasks["outcome"].value_counts(),
    "from envelopes": g.tasks["outcome"].value_counts(),
}).fillna(0).astype(int)
comparison
""")

code("""
pd.DataFrame({
    name: {"rows": len(g[name]), "id_certain": int(g[name]["id_certain"].sum())}
    for name in ("tasks", "whispers", "deliberations", "handoffs")
}).T
""")

md("""
The population to draw conclusions about individual tasks from is a filter
away, and the counts hold either way.
""")

code("""
sure = g.tasks[g.tasks["id_certain"]]
sure[["task_id", "kind", "outcome", "confidence", "criticality"]].head()
""")

md("""
## 8. Redaction

Artefacts hold whatever the agent was working on. Pass a redactor and it sees
every one of them before anything reaches a table: task inputs and outputs,
the artefact under review and the corrected one, the values a patch writes,
free-text whisper answers and lapse defaults, the inputs of a minted
successor, and the copies a snapshot holds. The shape of the analysis
survives: counts, tags, policy references, patch paths and the reviewer's own
words about their decision.
""")

code("""
redacted = frames(from_coordinator(coord, workspace=WORKSPACE, redact=redact_artefacts))

print("override count intact:", len(redacted.overrides) == len(f.overrides))
print("patch paths kept:     ", sorted(redacted.patch_ops["top_path"].unique()))
print("tags kept:            ", sorted(redacted.overrides.explode("tags")["tags"].unique()))
print("based_on redacted:    ", redacted.overrides.iloc[0]["based_on"])
print("rationale kept:       ", redacted.overrides.iloc[0]["rationale"])
""")

md("""
## 9. Export

`Frames` iterates as `(name, table)` pairs, `as_dict()` gives the tables by
name, and `to_csv(directory)` writes one file per table. For a round trip that
keeps artefacts and tag lists as structures, write each table with
`to_parquet` or `to_pickle`.
""")

code("""
import tempfile, os

out = tempfile.mkdtemp()
paths = f.to_csv(out)
for path in paths:
    print(f"{os.path.getsize(path):>7} bytes  {os.path.basename(path)}")
""")

md("""
## Where next

This package is stage one of the
[analytics roadmap](https://github.com/BrightbeamAI/chap/blob/main/ANALYTICS_ROADMAP.md):
the tables, documented and checked against the coordinator. Stage two adds
rates with intervals and censored durations. Stage three adds calibration,
reviewer severity, inter-rater agreement and drift. Stage four exports
evaluation cases and prompt-revision candidates. Stage five draws it.

The package README covers the loaders, the schema and the identity question in
full: https://github.com/BrightbeamAI/chap/tree/main/packages/chap-analytics
""")


def build() -> nbformat.NotebookNode:
    nb = new_notebook()
    nb.metadata["kernelspec"] = {"name": "python3", "display_name": "Python 3", "language": "python"}
    nb.metadata["language_info"] = {"name": "python"}
    for kind, text in CELLS:
        nb.cells.append(new_markdown_cell(text) if kind == "markdown" else new_code_cell(text))
    return nb


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--no-run", action="store_true", help="write the notebook and skip execution")
    args = parser.parse_args(argv)

    nb = build()
    if not args.no_run:
        from nbclient import NotebookClient
        NotebookClient(nb, timeout=300, kernel_name="python3", resources={"metadata": {"path": str(HERE)}}).execute()
    nbformat.write(nb, str(TARGET))
    print(f"wrote {TARGET.relative_to(HERE.parent)} ({len(nb.cells)} cells)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
